dist: trusty
sudo: false
language: scala
scala:
- 2.12.4
- 2.11.11
jdk: oraclejdk8
script: sbt ++$TRAVIS_SCALA_VERSION clean coverage test
after_success: if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then sbt ++$TRAVIS_SCALA_VERSION
  coverageReport coveralls; sbt ++$TRAVIS_SCALA_VERSION releaseEarly; fi
notifications:
  slack:
    on_success: never
    on_failure: always
    rooms:
      secure: ZkG0Ru1NcqJdGuf6gesro4xhAwU/zYCrU3FUOksYMtsdhd+SbVwLNXLlcBXZRQmsPKOPfC6McEyO6jc5Y05SXBkTNBzOw8Fe/bxEbBKYnxLQY7QrimfMstDu5Rz7xksNGDGiVxwXR+OtF3ixS6hzCR1rrHDrYmFQ/lPMGU+kyTJ54Vu81CBrhNbbuhswMx2N+QFLQDv090o8PgXa6YJJRo4k2qReQcZ6h7cCMVgfqzuJda/kmShl6HnOU4RjsIT5TLYWobLFdTJzPQdjtpASdwJyu2LAjF72BeO5jlNNp5eufrkRCaFbSt+NEYXV63DQqSb0QrPmur/n8M4RgumReDxNK3wPqrL4TanLsMcmTMEzVt2/GKJvt1HEila9HdLiZBhhDjV5NaekEbMmxh9azwUN2xpP6wlHbe3TkZsnly1r5V62hKePXP61Gatlp1HIXIGvfyLCDDyrvVzy1K+EELi3qDD865xgMJFB8BfRth6DUTzuc46Sqv/Iq03edp6VVUh9LUzrp4pU2BLsjMHU/aii+e5eoeqHLOzTphkZByg07z2zv9Jk27vgR1PO4G+LVV4l3RJVT8bU4mzV5ONX4k9Ss2UGaMQbvtao0hQGAo6XdRDyh3NfJVq/YG+vcDJZjOOsaUxlZRv2XWFpX6eiEu3sxYCz3kscmV0359HDeQ8=
env:
  global:
  - secure: BotqpBO79XrdI8m7JyGN1PuXjbMyUmEwvW5RR7aexTurWR7s03X3e9b/0/fiC+KBmYBbSXnfrxWJNGTm7trJEUsfK400rhm+LO4btCP8JJQw1jLoeT3FpC0GR1bG3NF1b9EBfXZm3IvEkBOWe9I/0NAhz7zH381hzgfybOssYj1NqxqAd1qTW4CZpSrZgZ9B6IV+cWcpOBZriZW4KorToU0WmdQBaf82A6t78MdB3iByUYI7fPUFuNNSQzwVcAWKvpdB9Cxbre29rGzdeJorawAEsgYevL/5ZsDL932KprbRFh92zbFHqt6ZVlZeaPhMJIXhx/W88m63KBynusi8jvBNxA8Ch0yajYtkPqVVcbV1f9XOJL2nSiD/VUWyFEqVAivqn5znYTGNNCxDF7gvINwr8UIlb84Sa94xK55D5mx8my0QvuctRDTLG/XF0l4hcXO/oMKNDcT5iDSSryOVDFDAt4jdFArLwPCa2G1j9pMzBENnWAZSTTzys3z0t3ehStKWwRUXRqoPhPNbmdmjvmqsernWWtd4Cu3lonE6jkJBxRz0kd2ai6Iw9gF1HJjQz+9/fyBA+gPAlraARc1GhwMVz330gxNk1Rj/dC3RIyp2qvKOvzD4OhPErLazDIfUv+tJi/+j/+vj40OaeMKTzacLu1+Kf4azykvfTImPfIY=
  - secure: pXLGdZ9UoFrvFFxR6GWXnk6sD7C8M68//zARlIRgS7TSCrVFmR/ZX5c9MoJWrBlak0Dl3Hxu9tpEKOKsL/ACA1Fnfhor662EocDb8yzj/zZ/0sYELeW85g2Zdox3UDFMjk0/4SiXKu2yUffy3T112U8E5iRauMcpchFYBWPYkWApglJrES5LMHOkGxBLKX8ZFqfGidS4ro7y+wQxIyKKy2keQc0hCfdKojQdhM8mOsugT4Sc+T+AKXTqy24nmetXGM6Onbob2E9CClSAdK2ydrOO9aAuXudedV4MHU/sgx4co0q3YjvtBOkRwmN2I8dzuccDxHfNu8V9xjIpHTHxAIvLHitK6zKqgRmxHBjtmd72uhocNmIFNTES5AfTbaYvppSSVyr76SgBohdWFzIm7UnphFlNpjgs9BNU7guozJ/nF+LZfzoEDIruur4RUYXssK02/3YSEa43l6/Ap9hy/NzoJExLUs8EDFWYu7YI/j4RLVzvf+EuCL48lGvCmslscWl72HMfJveJi3U248YFsIWelilWRwpAZ1D+PhXTmxRQvN7wHdIhJkufcbCaNJehWSAOA8uRZ8zNS3o8B0/FV+0HGbfxJk6HksoI/Jk6/7ZpJZfDnaOf9fgSZnEbSIxt7HyKjUGgrpsWQ5LgTNUU7VkbGUq7x8A7H3yMxxrdi5c=
